services:
    quant-app:
        build: .
        container_name: quant-finance
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - .:/app
        command: python LS_historic.py
